-- Xóa dữ liệu cũ (nếu có) để tránh lỗi trùng lặp ID
TRUNCATE TABLE answer_image, question_image, answer, exam_question, question, exam RESTART IDENTITY CASCADE;

-- 1. Tạo 2 Exam
INSERT INTO exam (id, code, type, created_date, updated_date, name, subject_name, description) VALUES
(1, 'EXAM001', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Midterm Biology Exam', 'Biology', 'Thi giữa kì môn Sinh học'),
(2, 'EXAM002', 'DEFAULT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Final Biology Exam', 'Biology', 'Thi cuối kì môn Sinh học');

-- 2. Tạo 60 Question (Mỗi Exam 30 câu)
INSERT INTO question (id, type, content, created_date, updated_date, explanation, description) VALUES
(1, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 1', 'Mô tả câu 1'),
(2, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 2', 'Mô tả câu 2'),
(3, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 3', 'Mô tả câu 3'),
(4, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 4', 'Mô tả câu 4'),
(5, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 5', 'Mô tả câu 5'),
(6, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 6', 'Mô tả câu 6'),
(7, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 7', 'Mô tả câu 7'),
(8, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 8', 'Mô tả câu 8'),
(9, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 9', 'Mô tả câu 9'),
(10, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 10', 'Mô tả câu 10'),
(11, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 11', 'Mô tả câu 11'),
(12, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 12', 'Mô tả câu 12'),
(13, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 13', 'Mô tả câu 13'),
(14, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 14', 'Mô tả câu 14'),
(15, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 15', 'Mô tả câu 15'),
(16, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 16', 'Mô tả câu 16'),
(17, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 17', 'Mô tả câu 17'),
(18, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 18', 'Mô tả câu 18'),
(19, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 19', 'Mô tả câu 19'),
(20, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 20', 'Mô tả câu 20'),
(21, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 21', 'Mô tả câu 21'),
(22, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 22', 'Mô tả câu 22'),
(23, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 23', 'Mô tả câu 23'),
(24, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 24', 'Mô tả câu 24'),
(25, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 25', 'Mô tả câu 25'),
(26, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 26', 'Mô tả câu 26'),
(27, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 27', 'Mô tả câu 27'),
(28, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 28', 'Mô tả câu 28'),
(29, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 29', 'Mô tả câu 29'),
(30, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 30', 'Mô tả câu 30'),
(31, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 31', 'Mô tả câu 31'),
(32, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 32', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 32', 'Mô tả câu 32'),
(33, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 33', 'Mô tả câu 33'),
(34, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 34', 'Mô tả câu 34'),
(35, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 35', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 35', 'Mô tả câu 35'),
(36, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 36', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 36', 'Mô tả câu 36'),
(37, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 37', 'Mô tả câu 37'),
(38, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 38', 'Mô tả câu 38'),
(39, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 39', 'Mô tả câu 39'),
(40, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 40', 'Mô tả câu 40'),
(41, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 41', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 41', 'Mô tả câu 41'),
(42, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 42', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 42', 'Mô tả câu 42'),
(43, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 43', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 43', 'Mô tả câu 43'),
(44, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 44', 'Mô tả câu 44'),
(45, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 45', 'Mô tả câu 45'),
(46, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 46', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 46', 'Mô tả câu 46'),
(47, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 47', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 47', 'Mô tả câu 47'),
(48, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 48', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 48', 'Mô tả câu 48'),
(49, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 49', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 49', 'Mô tả câu 49'),
(50, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 50', 'Mô tả câu 50'),
(51, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 51', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 51', 'Mô tả câu 51'),
(52, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 52', 'Mô tả câu 52'),
(53, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 53', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 53', 'Mô tả câu 53'),
(54, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 54', 'Mô tả câu 54'),
(55, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 55', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 55', 'Mô tả câu 55'),
(56, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 56', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 56', 'Mô tả câu 56'),
(57, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 57', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 57', 'Mô tả câu 57'),
(58, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 58', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 58', 'Mô tả câu 58'),
(59, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 59', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 59', 'Mô tả câu 59'),
(60, 'MULTIPLE_CHOICE', 'Nội dung câu hỏi số 60', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích cho câu 60', 'Mô tả câu 60');

-- 3. Link Questions to Exams (ExamQuestion)
INSERT INTO exam_question (id, point, question_order, created_date, updated_date, exam_id, question_id) VALUES
(1, 1.0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
(2, 1.0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 2),
(3, 1.0, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 3),
(4, 1.0, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 4),
(5, 1.0, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 5),
(6, 1.0, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 6),
(7, 1.0, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 7),
(8, 1.0, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 8),
(9, 1.0, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 9),
(10, 1.0, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 10),
(11, 1.0, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 11),
(12, 1.0, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 12),
(13, 1.0, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 13),
(14, 1.0, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 14),
(15, 1.0, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 15),
(16, 1.0, 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 16),
(17, 1.0, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 17),
(18, 1.0, 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 18),
(19, 1.0, 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 19),
(20, 1.0, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 20),
(21, 1.0, 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 21),
(22, 1.0, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 22),
(23, 1.0, 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 23),
(24, 1.0, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 24),
(25, 1.0, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 25),
(26, 1.0, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 26),
(27, 1.0, 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 27),
(28, 1.0, 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 28),
(29, 1.0, 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 29),
(30, 1.0, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 30),
(31, 1.0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 31),
(32, 1.0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 32),
(33, 1.0, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 33),
(34, 1.0, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 34),
(35, 1.0, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 35),
(36, 1.0, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 36),
(37, 1.0, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 37),
(38, 1.0, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 38),
(39, 1.0, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 39),
(40, 1.0, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 40),
(41, 1.0, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 41),
(42, 1.0, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 42),
(43, 1.0, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 43),
(44, 1.0, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 44),
(45, 1.0, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 45),
(46, 1.0, 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 46),
(47, 1.0, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 47),
(48, 1.0, 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 48),
(49, 1.0, 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 49),
(50, 1.0, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 50),
(51, 1.0, 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 51),
(52, 1.0, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 52),
(53, 1.0, 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 53),
(54, 1.0, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 54),
(55, 1.0, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 55),
(56, 1.0, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 56),
(57, 1.0, 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 57),
(58, 1.0, 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 58),
(59, 1.0, 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 59),
(60, 1.0, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 60);

-- 4. Tạo 4 Answer cho mỗi Question (Tổng 240 Answers)
INSERT INTO answer (id, type, content, created_date, updated_date, explanation, description, is_correct, question_id) VALUES
(1, 'TEXT', 'Đáp án 1 cho câu 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 1),
(2, 'TEXT', 'Đáp án 2 cho câu 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 1),
(3, 'TEXT', 'Đáp án 3 cho câu 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 1),
(4, 'TEXT', 'Đáp án 4 cho câu 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 1),
(5, 'TEXT', 'Đáp án 1 cho câu 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 2),
(6, 'TEXT', 'Đáp án 2 cho câu 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 2),
(7, 'TEXT', 'Đáp án 3 cho câu 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 2),
(8, 'TEXT', 'Đáp án 4 cho câu 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 2),
(9, 'TEXT', 'Đáp án 1 cho câu 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 3),
(10, 'TEXT', 'Đáp án 2 cho câu 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 3),
(11, 'TEXT', 'Đáp án 3 cho câu 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 3),
(12, 'TEXT', 'Đáp án 4 cho câu 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 3),
(13, 'TEXT', 'Đáp án 1 cho câu 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 4),
(14, 'TEXT', 'Đáp án 2 cho câu 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 4),
(15, 'TEXT', 'Đáp án 3 cho câu 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 4),
(16, 'TEXT', 'Đáp án 4 cho câu 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 4),
(17, 'TEXT', 'Đáp án 1 cho câu 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 5),
(18, 'TEXT', 'Đáp án 2 cho câu 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 5),
(19, 'TEXT', 'Đáp án 3 cho câu 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 5),
(20, 'TEXT', 'Đáp án 4 cho câu 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 5),
(21, 'TEXT', 'Đáp án 1 cho câu 6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 6),
(22, 'TEXT', 'Đáp án 2 cho câu 6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 6),
(23, 'TEXT', 'Đáp án 3 cho câu 6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 6),
(24, 'TEXT', 'Đáp án 4 cho câu 6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 6),
(25, 'TEXT', 'Đáp án 1 cho câu 7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 7),
(26, 'TEXT', 'Đáp án 2 cho câu 7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 7),
(27, 'TEXT', 'Đáp án 3 cho câu 7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 7),
(28, 'TEXT', 'Đáp án 4 cho câu 7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 7),
(29, 'TEXT', 'Đáp án 1 cho câu 8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 8),
(30, 'TEXT', 'Đáp án 2 cho câu 8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 8),
(31, 'TEXT', 'Đáp án 3 cho câu 8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 8),
(32, 'TEXT', 'Đáp án 4 cho câu 8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 8),
(33, 'TEXT', 'Đáp án 1 cho câu 9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 9),
(34, 'TEXT', 'Đáp án 2 cho câu 9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 9),
(35, 'TEXT', 'Đáp án 3 cho câu 9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 9),
(36, 'TEXT', 'Đáp án 4 cho câu 9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 9),
(37, 'TEXT', 'Đáp án 1 cho câu 10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 10),
(38, 'TEXT', 'Đáp án 2 cho câu 10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 10),
(39, 'TEXT', 'Đáp án 3 cho câu 10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 10),
(40, 'TEXT', 'Đáp án 4 cho câu 10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 10),
(41, 'TEXT', 'Đáp án 1 cho câu 11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 11),
(42, 'TEXT', 'Đáp án 2 cho câu 11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 11),
(43, 'TEXT', 'Đáp án 3 cho câu 11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 11),
(44, 'TEXT', 'Đáp án 4 cho câu 11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 11),
(45, 'TEXT', 'Đáp án 1 cho câu 12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 12),
(46, 'TEXT', 'Đáp án 2 cho câu 12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 12),
(47, 'TEXT', 'Đáp án 3 cho câu 12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 12),
(48, 'TEXT', 'Đáp án 4 cho câu 12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 12),
(49, 'TEXT', 'Đáp án 1 cho câu 13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 13),
(50, 'TEXT', 'Đáp án 2 cho câu 13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 13),
(51, 'TEXT', 'Đáp án 3 cho câu 13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 13),
(52, 'TEXT', 'Đáp án 4 cho câu 13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 13),
(53, 'TEXT', 'Đáp án 1 cho câu 14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 14),
(54, 'TEXT', 'Đáp án 2 cho câu 14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 14),
(55, 'TEXT', 'Đáp án 3 cho câu 14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 14),
(56, 'TEXT', 'Đáp án 4 cho câu 14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 14),
(57, 'TEXT', 'Đáp án 1 cho câu 15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 15),
(58, 'TEXT', 'Đáp án 2 cho câu 15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 15),
(59, 'TEXT', 'Đáp án 3 cho câu 15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 15),
(60, 'TEXT', 'Đáp án 4 cho câu 15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 15),
(61, 'TEXT', 'Đáp án 1 cho câu 16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 16),
(62, 'TEXT', 'Đáp án 2 cho câu 16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 16),
(63, 'TEXT', 'Đáp án 3 cho câu 16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 16),
(64, 'TEXT', 'Đáp án 4 cho câu 16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 16),
(65, 'TEXT', 'Đáp án 1 cho câu 17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 17),
(66, 'TEXT', 'Đáp án 2 cho câu 17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 17),
(67, 'TEXT', 'Đáp án 3 cho câu 17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 17),
(68, 'TEXT', 'Đáp án 4 cho câu 17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 17),
(69, 'TEXT', 'Đáp án 1 cho câu 18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 18),
(70, 'TEXT', 'Đáp án 2 cho câu 18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 18),
(71, 'TEXT', 'Đáp án 3 cho câu 18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 18),
(72, 'TEXT', 'Đáp án 4 cho câu 18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 18),
(73, 'TEXT', 'Đáp án 1 cho câu 19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 19),
(74, 'TEXT', 'Đáp án 2 cho câu 19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 19),
(75, 'TEXT', 'Đáp án 3 cho câu 19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 19),
(76, 'TEXT', 'Đáp án 4 cho câu 19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 19),
(77, 'TEXT', 'Đáp án 1 cho câu 20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 20),
(78, 'TEXT', 'Đáp án 2 cho câu 20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 20),
(79, 'TEXT', 'Đáp án 3 cho câu 20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 20),
(80, 'TEXT', 'Đáp án 4 cho câu 20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 20),
(81, 'TEXT', 'Đáp án 1 cho câu 21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 21),
(82, 'TEXT', 'Đáp án 2 cho câu 21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 21),
(83, 'TEXT', 'Đáp án 3 cho câu 21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 21),
(84, 'TEXT', 'Đáp án 4 cho câu 21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 21),
(85, 'TEXT', 'Đáp án 1 cho câu 22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 22),
(86, 'TEXT', 'Đáp án 2 cho câu 22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 22),
(87, 'TEXT', 'Đáp án 3 cho câu 22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 22),
(88, 'TEXT', 'Đáp án 4 cho câu 22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 22),
(89, 'TEXT', 'Đáp án 1 cho câu 23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 23),
(90, 'TEXT', 'Đáp án 2 cho câu 23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 23),
(91, 'TEXT', 'Đáp án 3 cho câu 23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 23),
(92, 'TEXT', 'Đáp án 4 cho câu 23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 23),
(93, 'TEXT', 'Đáp án 1 cho câu 24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 24),
(94, 'TEXT', 'Đáp án 2 cho câu 24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 24),
(95, 'TEXT', 'Đáp án 3 cho câu 24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 24),
(96, 'TEXT', 'Đáp án 4 cho câu 24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 24),
(97, 'TEXT', 'Đáp án 1 cho câu 25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 25),
(98, 'TEXT', 'Đáp án 2 cho câu 25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 25),
(99, 'TEXT', 'Đáp án 3 cho câu 25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 25),
(100, 'TEXT', 'Đáp án 4 cho câu 25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 25),
(101, 'TEXT', 'Đáp án 1 cho câu 26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 26),
(102, 'TEXT', 'Đáp án 2 cho câu 26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 26),
(103, 'TEXT', 'Đáp án 3 cho câu 26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 26),
(104, 'TEXT', 'Đáp án 4 cho câu 26', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 26),
(105, 'TEXT', 'Đáp án 1 cho câu 27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 27),
(106, 'TEXT', 'Đáp án 2 cho câu 27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 27),
(107, 'TEXT', 'Đáp án 3 cho câu 27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 27),
(108, 'TEXT', 'Đáp án 4 cho câu 27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 27),
(109, 'TEXT', 'Đáp án 1 cho câu 28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 28),
(110, 'TEXT', 'Đáp án 2 cho câu 28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 28),
(111, 'TEXT', 'Đáp án 3 cho câu 28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 28),
(112, 'TEXT', 'Đáp án 4 cho câu 28', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 28),
(113, 'TEXT', 'Đáp án 1 cho câu 29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 29),
(114, 'TEXT', 'Đáp án 2 cho câu 29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 29),
(115, 'TEXT', 'Đáp án 3 cho câu 29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 29),
(116, 'TEXT', 'Đáp án 4 cho câu 29', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 29),
(117, 'TEXT', 'Đáp án 1 cho câu 30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 30),
(118, 'TEXT', 'Đáp án 2 cho câu 30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 30),
(119, 'TEXT', 'Đáp án 3 cho câu 30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 30),
(120, 'TEXT', 'Đáp án 4 cho câu 30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 30),
(121, 'TEXT', 'Đáp án 1 cho câu 31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 31),
(122, 'TEXT', 'Đáp án 2 cho câu 31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 31),
(123, 'TEXT', 'Đáp án 3 cho câu 31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 31),
(124, 'TEXT', 'Đáp án 4 cho câu 31', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 31),
(125, 'TEXT', 'Đáp án 1 cho câu 32', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 32),
(126, 'TEXT', 'Đáp án 2 cho câu 32', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 32),
(127, 'TEXT', 'Đáp án 3 cho câu 32', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 32),
(128, 'TEXT', 'Đáp án 4 cho câu 32', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 32),
(129, 'TEXT', 'Đáp án 1 cho câu 33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 33),
(130, 'TEXT', 'Đáp án 2 cho câu 33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 33),
(131, 'TEXT', 'Đáp án 3 cho câu 33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 33),
(132, 'TEXT', 'Đáp án 4 cho câu 33', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 33),
(133, 'TEXT', 'Đáp án 1 cho câu 34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 34),
(134, 'TEXT', 'Đáp án 2 cho câu 34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 34),
(135, 'TEXT', 'Đáp án 3 cho câu 34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 34),
(136, 'TEXT', 'Đáp án 4 cho câu 34', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 34),
(137, 'TEXT', 'Đáp án 1 cho câu 35', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 35),
(138, 'TEXT', 'Đáp án 2 cho câu 35', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 35),
(139, 'TEXT', 'Đáp án 3 cho câu 35', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 35),
(140, 'TEXT', 'Đáp án 4 cho câu 35', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 35),
(141, 'TEXT', 'Đáp án 1 cho câu 36', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 36),
(142, 'TEXT', 'Đáp án 2 cho câu 36', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 36),
(143, 'TEXT', 'Đáp án 3 cho câu 36', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 36),
(144, 'TEXT', 'Đáp án 4 cho câu 36', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 36),
(145, 'TEXT', 'Đáp án 1 cho câu 37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 37),
(146, 'TEXT', 'Đáp án 2 cho câu 37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 37),
(147, 'TEXT', 'Đáp án 3 cho câu 37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 37),
(148, 'TEXT', 'Đáp án 4 cho câu 37', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 37),
(149, 'TEXT', 'Đáp án 1 cho câu 38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 38),
(150, 'TEXT', 'Đáp án 2 cho câu 38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 38),
(151, 'TEXT', 'Đáp án 3 cho câu 38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 38),
(152, 'TEXT', 'Đáp án 4 cho câu 38', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 38),
(153, 'TEXT', 'Đáp án 1 cho câu 39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 39),
(154, 'TEXT', 'Đáp án 2 cho câu 39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 39),
(155, 'TEXT', 'Đáp án 3 cho câu 39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 39),
(156, 'TEXT', 'Đáp án 4 cho câu 39', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 39),
(157, 'TEXT', 'Đáp án 1 cho câu 40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 40),
(158, 'TEXT', 'Đáp án 2 cho câu 40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 40),
(159, 'TEXT', 'Đáp án 3 cho câu 40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 40),
(160, 'TEXT', 'Đáp án 4 cho câu 40', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 40),
(161, 'TEXT', 'Đáp án 1 cho câu 41', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 41),
(162, 'TEXT', 'Đáp án 2 cho câu 41', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 41),
(163, 'TEXT', 'Đáp án 3 cho câu 41', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 41),
(164, 'TEXT', 'Đáp án 4 cho câu 41', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 41),
(165, 'TEXT', 'Đáp án 1 cho câu 42', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 42),
(166, 'TEXT', 'Đáp án 2 cho câu 42', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 42),
(167, 'TEXT', 'Đáp án 3 cho câu 42', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 42),
(168, 'TEXT', 'Đáp án 4 cho câu 42', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 42),
(169, 'TEXT', 'Đáp án 1 cho câu 43', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 43),
(170, 'TEXT', 'Đáp án 2 cho câu 43', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 43),
(171, 'TEXT', 'Đáp án 3 cho câu 43', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 43),
(172, 'TEXT', 'Đáp án 4 cho câu 43', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 43),
(173, 'TEXT', 'Đáp án 1 cho câu 44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 44),
(174, 'TEXT', 'Đáp án 2 cho câu 44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 44),
(175, 'TEXT', 'Đáp án 3 cho câu 44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 44),
(176, 'TEXT', 'Đáp án 4 cho câu 44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 44),
(177, 'TEXT', 'Đáp án 1 cho câu 45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 45),
(178, 'TEXT', 'Đáp án 2 cho câu 45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 45),
(179, 'TEXT', 'Đáp án 3 cho câu 45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 45),
(180, 'TEXT', 'Đáp án 4 cho câu 45', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 45),
(181, 'TEXT', 'Đáp án 1 cho câu 46', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 46),
(182, 'TEXT', 'Đáp án 2 cho câu 46', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 46),
(183, 'TEXT', 'Đáp án 3 cho câu 46', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 46),
(184, 'TEXT', 'Đáp án 4 cho câu 46', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 46),
(185, 'TEXT', 'Đáp án 1 cho câu 47', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 47),
(186, 'TEXT', 'Đáp án 2 cho câu 47', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 47),
(187, 'TEXT', 'Đáp án 3 cho câu 47', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 47),
(188, 'TEXT', 'Đáp án 4 cho câu 47', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 47),
(189, 'TEXT', 'Đáp án 1 cho câu 48', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 48),
(190, 'TEXT', 'Đáp án 2 cho câu 48', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 48),
(191, 'TEXT', 'Đáp án 3 cho câu 48', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 48),
(192, 'TEXT', 'Đáp án 4 cho câu 48', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 48),
(193, 'TEXT', 'Đáp án 1 cho câu 49', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 49),
(194, 'TEXT', 'Đáp án 2 cho câu 49', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 49),
(195, 'TEXT', 'Đáp án 3 cho câu 49', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 49),
(196, 'TEXT', 'Đáp án 4 cho câu 49', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 49),
(197, 'TEXT', 'Đáp án 1 cho câu 50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 50),
(198, 'TEXT', 'Đáp án 2 cho câu 50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 50),
(199, 'TEXT', 'Đáp án 3 cho câu 50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 50),
(200, 'TEXT', 'Đáp án 4 cho câu 50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 50),
(201, 'TEXT', 'Đáp án 1 cho câu 51', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 51),
(202, 'TEXT', 'Đáp án 2 cho câu 51', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 51),
(203, 'TEXT', 'Đáp án 3 cho câu 51', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 51),
(204, 'TEXT', 'Đáp án 4 cho câu 51', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 51),
(205, 'TEXT', 'Đáp án 1 cho câu 52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 52),
(206, 'TEXT', 'Đáp án 2 cho câu 52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 52),
(207, 'TEXT', 'Đáp án 3 cho câu 52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 52),
(208, 'TEXT', 'Đáp án 4 cho câu 52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 52),
(209, 'TEXT', 'Đáp án 1 cho câu 53', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 53),
(210, 'TEXT', 'Đáp án 2 cho câu 53', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 53),
(211, 'TEXT', 'Đáp án 3 cho câu 53', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 53),
(212, 'TEXT', 'Đáp án 4 cho câu 53', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 53),
(213, 'TEXT', 'Đáp án 1 cho câu 54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 54),
(214, 'TEXT', 'Đáp án 2 cho câu 54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 54),
(215, 'TEXT', 'Đáp án 3 cho câu 54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 54),
(216, 'TEXT', 'Đáp án 4 cho câu 54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 54),
(217, 'TEXT', 'Đáp án 1 cho câu 55', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 55),
(218, 'TEXT', 'Đáp án 2 cho câu 55', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 55),
(219, 'TEXT', 'Đáp án 3 cho câu 55', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 55),
(220, 'TEXT', 'Đáp án 4 cho câu 55', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 55),
(221, 'TEXT', 'Đáp án 1 cho câu 56', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 56),
(222, 'TEXT', 'Đáp án 2 cho câu 56', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 56),
(223, 'TEXT', 'Đáp án 3 cho câu 56', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 56),
(224, 'TEXT', 'Đáp án 4 cho câu 56', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 56),
(225, 'TEXT', 'Đáp án 1 cho câu 57', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 57),
(226, 'TEXT', 'Đáp án 2 cho câu 57', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 57),
(227, 'TEXT', 'Đáp án 3 cho câu 57', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 57),
(228, 'TEXT', 'Đáp án 4 cho câu 57', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 57),
(229, 'TEXT', 'Đáp án 1 cho câu 58', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 58),
(230, 'TEXT', 'Đáp án 2 cho câu 58', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 58),
(231, 'TEXT', 'Đáp án 3 cho câu 58', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 58),
(232, 'TEXT', 'Đáp án 4 cho câu 58', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 58),
(233, 'TEXT', 'Đáp án 1 cho câu 59', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 59),
(234, 'TEXT', 'Đáp án 2 cho câu 59', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 59),
(235, 'TEXT', 'Đáp án 3 cho câu 59', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 59),
(236, 'TEXT', 'Đáp án 4 cho câu 59', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 59),
(237, 'TEXT', 'Đáp án 1 cho câu 60', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', TRUE, 60),
(238, 'TEXT', 'Đáp án 2 cho câu 60', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 60),
(239, 'TEXT', 'Đáp án 3 cho câu 60', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 60),
(240, 'TEXT', 'Đáp án 4 cho câu 60', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Giải thích đáp án', 'Mô tả', FALSE, 60);

-- 5. Tạo Question Images (Cho một nửa số câu hỏi)
INSERT INTO question_image (id, name, display_order, created_date, url, question_id) VALUES
(1, 'q_img_1.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q1.jpg', 1),
(2, 'q_img_3.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q3.jpg', 3),
(3, 'q_img_5.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q5.jpg', 5),
(4, 'q_img_7.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q7.jpg', 7),
(5, 'q_img_9.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q9.jpg', 9),
(6, 'q_img_11.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q11.jpg', 11),
(7, 'q_img_13.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q13.jpg', 13),
(8, 'q_img_15.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q15.jpg', 15),
(9, 'q_img_17.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q17.jpg', 17),
(10, 'q_img_19.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q19.jpg', 19),
(11, 'q_img_21.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q21.jpg', 21),
(12, 'q_img_23.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q23.jpg', 23),
(13, 'q_img_25.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q25.jpg', 25),
(14, 'q_img_27.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q27.jpg', 27),
(15, 'q_img_29.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q29.jpg', 29),
(16, 'q_img_31.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q31.jpg', 31),
(17, 'q_img_33.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q33.jpg', 33),
(18, 'q_img_35.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q35.jpg', 35),
(19, 'q_img_37.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q37.jpg', 37),
(20, 'q_img_39.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q39.jpg', 39),
(21, 'q_img_41.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q41.jpg', 41),
(22, 'q_img_43.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q43.jpg', 43),
(23, 'q_img_45.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q45.jpg', 45),
(24, 'q_img_47.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q47.jpg', 47),
(25, 'q_img_49.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q49.jpg', 49),
(26, 'q_img_51.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q51.jpg', 51),
(27, 'q_img_53.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q53.jpg', 53),
(28, 'q_img_55.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q55.jpg', 55),
(29, 'q_img_57.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q57.jpg', 57),
(30, 'q_img_59.jpg', 1, CURRENT_TIMESTAMP, 'https://example.com/q59.jpg', 59);

-- 6. Tạo Answer Images (Cho một vài đáp án ngẫu nhiên)
INSERT INTO answer_image (id, name, display_order, created_date, url, answer_id) VALUES
(1, 'a_img_1.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a1.png', 1),
(2, 'a_img_6.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a6.png', 6),
(3, 'a_img_11.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a11.png', 11),
(4, 'a_img_16.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a16.png', 16),
(5, 'a_img_21.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a21.png', 21),
(6, 'a_img_26.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a26.png', 26),
(7, 'a_img_31.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a31.png', 31),
(8, 'a_img_36.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a36.png', 36),
(9, 'a_img_41.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a41.png', 41),
(10, 'a_img_46.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a46.png', 46),
(11, 'a_img_51.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a51.png', 51),
(12, 'a_img_56.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a56.png', 56),
(13, 'a_img_61.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a61.png', 61),
(14, 'a_img_66.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a66.png', 66),
(15, 'a_img_71.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a71.png', 71),
(16, 'a_img_76.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a76.png', 76),
(17, 'a_img_81.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a81.png', 81),
(18, 'a_img_86.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a86.png', 86),
(19, 'a_img_91.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a91.png', 91),
(20, 'a_img_96.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a96.png', 96),
(21, 'a_img_101.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a101.png', 101),
(22, 'a_img_106.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a106.png', 106),
(23, 'a_img_111.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a111.png', 111),
(24, 'a_img_116.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a116.png', 116),
(25, 'a_img_121.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a121.png', 121),
(26, 'a_img_126.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a126.png', 126),
(27, 'a_img_131.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a131.png', 131),
(28, 'a_img_136.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a136.png', 136),
(29, 'a_img_141.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a141.png', 141),
(30, 'a_img_146.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a146.png', 146),
(31, 'a_img_151.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a151.png', 151),
(32, 'a_img_156.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a156.png', 156),
(33, 'a_img_161.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a161.png', 161),
(34, 'a_img_166.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a166.png', 166),
(35, 'a_img_171.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a171.png', 171),
(36, 'a_img_176.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a176.png', 176),
(37, 'a_img_181.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a181.png', 181),
(38, 'a_img_186.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a186.png', 186),
(39, 'a_img_191.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a191.png', 191),
(40, 'a_img_196.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a196.png', 196),
(41, 'a_img_201.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a201.png', 201),
(42, 'a_img_206.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a206.png', 206),
(43, 'a_img_211.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a211.png', 211),
(44, 'a_img_216.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a216.png', 216),
(45, 'a_img_221.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a221.png', 221),
(46, 'a_img_226.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a226.png', 226),
(47, 'a_img_231.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a231.png', 231),
(48, 'a_img_236.png', 1, CURRENT_TIMESTAMP, 'https://example.com/a236.png', 236);

-- 7. Cập nhật lại sequence cho các bảng để tránh lỗi khi insert tay sau này
SELECT setval('exam_id_seq', (SELECT MAX(id) FROM exam));
SELECT setval('question_id_seq', (SELECT MAX(id) FROM question));
SELECT setval('exam_question_id_seq', (SELECT MAX(id) FROM exam_question));
SELECT setval('answer_id_seq', (SELECT MAX(id) FROM answer));
SELECT setval('question_image_id_seq', (SELECT MAX(id) FROM question_image));
SELECT setval('answer_image_id_seq', (SELECT MAX(id) FROM answer_image));
