-- ============================================================
-- V22: Seed Physics 3D Models, Categories and Labs
-- Mô hình 3D Vật lý (Lớp 6-8 và Lớp 7-9) cho BioVerse
-- ============================================================

-- 1. Ensure Categories for Physics
INSERT INTO bio_model_categories (name, slug, subject, sort_order, is_active) VALUES
    ('Cơ học', 'co-hoc', 'PHYSICS', 11, TRUE),
    ('Điện học', 'dien-hoc', 'PHYSICS', 12, TRUE),
    ('Dụng cụ đo điện', 'dung-cu-do-dien', 'PHYSICS', 13, TRUE),
    ('Điện từ học', 'dien-tu-hoc', 'PHYSICS', 14, TRUE),
    ('Từ học', 'tu-hoc', 'PHYSICS', 15, TRUE)
ON CONFLICT (name) DO UPDATE SET
    subject = EXCLUDED.subject,
    is_active = TRUE;

-- 2. Ensure Labs for Physics
INSERT INTO bio_labs (code, name, description, is_system, sort_order, is_active) VALUES
    ('pulley', 'Ròng rọc', 'Mô phỏng hệ thống ròng rọc cơ học và định luật bảo toàn công.', FALSE, 11, TRUE),
    ('spring', 'Lò xo đàn hồi', 'Mô phỏng độ dãn của lò xo cuộn và định luật Hooke.', FALSE, 12, TRUE),
    ('circuit', 'Mạch điện', 'Mô phỏng sơ đồ mạch điện, nguồn điện và bóng đèn.', FALSE, 13, TRUE),
    ('instrument', 'Dụng cụ đo điện', 'Mô phỏng đồng hồ vôn kế và đồng hồ đo vạn năng.', FALSE, 14, TRUE),
    ('magnetic', 'Từ trường & Nam châm', 'Mô phỏng từ trường nam châm chữ U và đoàn tàu từ tính.', FALSE, 15, TRUE),
    ('battery', 'Pin & Nguồn điện', 'Mô phỏng mặt cắt cấu tạo bên trong pin điện hóa.', FALSE, 16, TRUE),
    ('solenoid', 'Cuộn dây Solenoid', 'Mô phỏng đường sức từ bên trong và bên ngoài ống dây có dòng điện.', FALSE, 17, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_active = TRUE;

-- 3. Seed 12 Physics 3D Models
INSERT INTO bio_models (
    name, name_en, slug, category, description,
    grade, subject, badge_text, action_text, action_icon, target_mode,
    model_url, thumbnail_url, model_format,
    classification, fun_facts,
    is_featured, sort_order, is_active, views_count
) VALUES
-- ===== Lớp 6-8 (Grade 6 - Cơ học & Điện học) =====
(
    'Hệ Thống Ròng Rọc',
    'Block and Tackle Pulley System',
    'he-thong-rong-roc',
    'Cơ học',
    'Mô hình 3D hệ thống ròng rọc (palăng / block & tackle) mô phỏng nguyên lý cơ học giảm lực kéo: kết hợp ròng rọc cố định và ròng rọc động cùng dây vắt qua các rãnh để nâng vật nặng dễ dàng.',
    6,
    'PHYSICS',
    'Cơ học',
    'Khám phá ngay',
    'settings',
    'pulley',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop6-8/block_and_tackle.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/0feeb96f-90df-4535-9242-377412599138.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    1,
    TRUE,
    150
),
(
    'Lò Xo Cuộn',
    'Coil Spring',
    'lo-xo-cuon',
    'Cơ học',
    'Mô hình 3D lò xo cuộn xoắn minh họa tính đàn hồi của vật thể, định luật Hooke và dao động cơ học trong chương trình Vật lý THCS.',
    6,
    'PHYSICS',
    'Đàn hồi',
    'Khám phá ngay',
    'compress',
    'spring',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop6-8/coil_spring.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/f4b4f454-32a0-4971-8601-473cefafbc6c.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    2,
    TRUE,
    120
),
(
    'Mạch Điện Cơ Bản',
    'Basic Electric Circuit',
    'mach-dien-co-ban',
    'Điện học',
    'Mô hình 3D mạch điện một chiều đơn giản gồm nguồn điện (pin), dây dẫn và bóng đèn, minh họa đường đi của dòng điện, hiệu điện thế và mạch kín.',
    6,
    'PHYSICS',
    'Điện học',
    'Khám phá ngay',
    'bolt',
    'circuit',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop6-8/electric_circuit.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/228438a3-95a2-43d0-b097-a9fc8c735eee.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    3,
    TRUE,
    210
),
(
    'Vôn Kế',
    'Voltmeter',
    'von-ke',
    'Dụng cụ đo điện',
    'Mô hình 3D đồng hồ đo hiệu điện thế (vôn kế) với mặt số kim chỉ thị rõ ràng, hai chốt cắm cực âm (-) và cực dương (+), phục vụ thực hành đo điện trong phòng thí nghiệm.',
    6,
    'PHYSICS',
    'Đo lường',
    'Khám phá ngay',
    'speed',
    'instrument',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop6-8/voltmeter.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/a519763e-41a2-4315-92b4-fb3d3b96d335.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    4,
    TRUE,
    180
),

-- ===== Lớp 7-9 (Grade 9 - Điện học, Từ học & Điện từ học) =====
(
    'Đoàn Tàu Điện Từ Trường',
    'Battery Magnetic Train',
    'tau-dien-tu-truong',
    'Điện từ học',
    'Mô hình 3D thí nghiệm đoàn tàu từ tính đơn giản: gồm viên pin gắn nam châm neodymium ở hai đầu tự chuyển động bên trong ống cuộn dây đồng nhờ tác dụng của lực từ Lorentz.',
    9,
    'PHYSICS',
    'Điện từ học',
    'Khám phá ngay',
    'train',
    'magnetic',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/battery_magnetic_train.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/44bd81b9-02dd-4f6e-9ccc-84b16f2132ac.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    5,
    TRUE,
    340
),
(
    'Bo Mạch Nối Dây (Breadboard)',
    'Breadboard',
    'breadboard-mach-dien',
    'Điện học',
    'Mô hình 3D bo cắm thử nghiệm mạch điện (breadboard) cho phép lắp ráp và kiểm thử các mạch điện tử nhanh chóng không cần hàn chì, hiển thị rõ cấu trúc các dải tiếp điểm bên trong.',
    9,
    'PHYSICS',
    'Điện tử',
    'Khám phá ngay',
    'developer_board',
    'circuit',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/breadboard.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/1c2b598f-05a4-4d13-a466-26ff6b64d479.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    6,
    TRUE,
    160
),
(
    'Cấu Tạo Pin Điện Hóa',
    'Cell Battery',
    'pin-dien-hoa',
    'Điện học',
    'Mô hình 3D mặt cắt cấu tạo bên trong của pin điện hóa: các lớp cực dương (cathode), cực âm (anode), dung dịch chất điện phân và vỏ bọc, minh họa chuyển hóa hóa năng thành điện năng.',
    9,
    'PHYSICS',
    'Nguồn điện',
    'Khám phá ngay',
    'battery_full',
    'battery',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/cell_battery__luna_has_gone_prop.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/7e32bc2b-dcf5-412f-ab57-ea866b7fe400.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    7,
    TRUE,
    195
),
(
    'Từ Trường Nam Châm Chữ U',
    'Horseshoe Magnet Field',
    'nam-cham-mong-ngua',
    'Từ học',
    'Mô hình 3D nam châm chữ U (nam châm hình móng ngựa) biểu diễn trực quan đường sức từ, hai cực Bắc (N) - Nam (S) và vùng từ trường đều đậm đặc tại khe hở giữa hai cực.',
    9,
    'PHYSICS',
    'Từ học',
    'Khám phá ngay',
    'magnet',
    'magnetic',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/feld-hufeisenmagnet.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/30699008-c498-4d94-b1f2-c8406b0b8eb8.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    TRUE,
    8,
    TRUE,
    420
),
(
    'Từ Trường Ống Dây Solenoid',
    'Magnetic Field of Solenoid',
    'tu-truong-cuon-day-solenoid',
    'Điện từ học',
    'Mô hình 3D mô phỏng phổ đường sức từ của ống dây có dòng điện chạy qua (solenoid), thể hiện rõ các đường sức từ song song và đều đặn bên trong lòng ống dây tương tự như một thanh nam châm thẳng.',
    9,
    'PHYSICS',
    'Điện từ trường',
    'Khám phá ngay',
    'wifi',
    'solenoid',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/magnetic_field_of_solenoid_by_yuyalyj.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/bb0809f7-cc80-4b46-954e-9f56ce17057d.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    9,
    TRUE,
    260
),
(
    'Đồng Hồ Vạn Năng',
    'Multimeter',
    'dong-ho-van-nang',
    'Dụng cụ đo điện',
    'Mô hình 3D đồng hồ đo điện vạn năng (VOM) đa chức năng: đo hiệu điện thế (Vôn), cường độ dòng điện (Ampe) và điện trở (Ohm), trang bị núm xoay chuyển thang đo và que đo âm dương.',
    9,
    'PHYSICS',
    'Đo lường',
    'Khám phá ngay',
    'tune',
    'instrument',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/multimeter_-_free.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/74ad5ddb-ecde-493d-a8d4-0d863a2b1131.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    10,
    TRUE,
    310
),
(
    'Cuộn Dây Điện Solenoid',
    'Solenoid Coil',
    'cuon-day-solenoid',
    'Điện từ học',
    'Mô hình 3D cuộn dây hình trụ quấn nhiều vòng (solenoid), minh họa cấu trúc lõi và các vòng dây kim loại dẫn điện ứng dụng làm nam châm điện hoặc rơ le trong đời sống.',
    9,
    'PHYSICS',
    'Cuộn dây',
    'Khám phá ngay',
    'rotate_right',
    'solenoid',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/solenoid_12fbx.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/e34d28c0-f1c3-4864-a382-dc64b534d859.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    11,
    TRUE,
    175
),
(
    'Vôn Kế Thí Nghiệm Tiêu Chuẩn',
    'Laboratory Voltmeter',
    'von-ke-chi-tiet',
    'Dụng cụ đo điện',
    'Mô hình 3D vôn kế khung quay tiêu chuẩn phòng thí nghiệm: thang đo vạch chia độ chính xác cao, vít chỉnh điểm không (zero), vỏ cách điện và các chốt nối cắm dây an toàn.',
    9,
    'PHYSICS',
    'Đo lường',
    'Khám phá ngay',
    'speed',
    'instrument',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/lop7-9/voltmeter-freepoly.org.glb',
    'https://pub-b282035203fc485cb0cd7dadcbb4f8ae.r2.dev/thumbnails/d94d7a1d-0b50-4e08-9438-6b89a81c158e.png',
    'glb',
    '{}'::jsonb,
    '[]'::jsonb,
    FALSE,
    12,
    TRUE,
    220
)
ON CONFLICT (slug) DO UPDATE SET
    name            = EXCLUDED.name,
    name_en         = EXCLUDED.name_en,
    category        = EXCLUDED.category,
    description     = EXCLUDED.description,
    grade           = EXCLUDED.grade,
    subject         = EXCLUDED.subject,
    badge_text      = EXCLUDED.badge_text,
    action_text     = EXCLUDED.action_text,
    action_icon     = EXCLUDED.action_icon,
    target_mode     = EXCLUDED.target_mode,
    model_url       = EXCLUDED.model_url,
    thumbnail_url   = EXCLUDED.thumbnail_url,
    model_format    = EXCLUDED.model_format,
    is_featured     = EXCLUDED.is_featured,
    sort_order      = EXCLUDED.sort_order,
    is_active       = EXCLUDED.is_active,
    updated_at      = NOW();
